name: CD

# on:
#   push:
#     branches: [ develop ]

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: CI
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 139.162.4.59
        password: a922830A.bl
        script: 'cd /var/www/html && chmod -R 777 ./'
