name: CD

# on:
#   push:
#     branches: [ develop ]

on:
  push:
    paths-ignore:
      - 'ci.yml'
      # - 'cd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: ci
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 139.162.4.59
        password: a922830A.bl
        script: 'cd /var/www/html && chmod -R 777 ./'
