# name: CD

# on:
#   push:
#     branches: [ develop ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - run: echo ${{ secrets.HOST }}
#     - name: Deploy using ssh
#       uses: appleboy/ssh-action@master
#       with:
#         host: '139.162.4.59'
#         username: root
#         key: ${{ secrets.PRIVATE_KEY }}
#         port: 22
#         script: |
#           cd ~/var/www/html
