name: CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo apt install sshpass

    - name: Deploy to Production
      run: |
        sshpass -p 'a922830A.bl' ssh root@139.162.4.59
