# name: CD

# on:
#   push:
#     branches: [ develop ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - run: echo ${{ secrets.HOST }}
#     - name: Deploy using ssh
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{secrets.HOST}}
#         username: ${{secrets.USER}}
#         key: ${{ secrets.PRIVATEY }}
#         passphrase: ${{ secrets.PASS }}
#         port: 22

name: CD

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USER}}
        host: ${{secrets.HOST}}
        key: ${{ secrets.PRIVATEY }}
        password: ${{ secrets.PASS }}
        script: 'cd /var/www/html'
